name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./nginx/auto/configure --user=www --group=www --prefix=/www/server/nginx --add-module=/rainginx/ngm/ngx_devel_kit --add-module=/www/server/nginx/src/lua_nginx_module --with-openssl=/rainginx/quictls --with-http_v2_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_stub_status_module --with-http_ssl_module --with-http_image_filter_module --with-http_gzip_static_module --with-http_gunzip_module --with-ipv6 --with-http_sub_module --with-http_flv_module --with-http_addition_module --with-http_realip_module --with-http_mp4_module --with-ld-opt=-Wl,-E --with-ld-opt=-ljemalloc --with-ld-opt="-L../boringssl/build/ssl -L../boringssl/build/crypto" --with-ld-opt=-Wl,-rpath,/usr/local/LuaJIT/lib --with-cc-opt=-Wno-error --with-http_dav_module --with-http_v3_module --with-cc-opt="-I../boringssl/include" --with-http_geoip_module --add-module=/rainginx/ngm/ngx_cache_purge --add-module=/rainginx/ngm/ngx_brotli --add-module=/rainginx/ngm/ngx_http_substitutions_filter_module --with-pcre=/rainginx/pcre --add-module=/rainginx/ngm/nginx-http-concat --add-module=/rainginx/ngm/nginx-dav-ext-module
    - name: cd
      run: cd nginx
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
